from app import db
class User(db.Model):
    key = db.Column(db.INTEGER, unique=True, nullable=False, primary_key=True)
    coordinator= db.Column(db.INTEGER,nullable=False)
    user_req = db.Column(db.INTEGER)
    site_code = db.Column(db.TEXT)
    submit_date = db.Column(db.DateTime)
    due_date = db.Column(db.DateTime)
    install  = db.Column(db.Boolean)
    change  = db.Column(db.Boolean)
    move  = db.Column(db.Boolean)
    disconnect  = db.Column(db.Boolean)
    requestor_name = db.Column(db.TEXT,nullable=False)
    email =db.Column(db.TEXT, nullable= False)
    telephone = db.Column(db.INTEGER)
    department = db.Column(db.TEXT)
    division = db.Column(db.TEXT)
    rc = db.Column(db.TEXT)
    address = db.Column(db.TEXT)
    room = db.Column(db.TEXT)
    depot = db.Column(db.TEXT)
    description = db.Column(db.TEXT)
    manager_name = db.Column(db.TEXT, nullable=False)
    manager_title = db.Column(db.TEXT)
    approval = db.Column(db.Boolean)
    floor = db.Column(db.TEXT)

    def __repr__(self):
        return '<User {},{},{},{},{}>'.format(self.manager_name,self.key,self.install, self.due_date, self.submit_date)    