"""users table

Revision ID: eb436194337b
Revises: 
Create Date: 2018-04-18 15:54:36.739249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb436194337b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('key', sa.INTEGER(), nullable=False),
    sa.Column('coordinator', sa.INTEGER(), nullable=False),
    sa.Column('user_req', sa.INTEGER(), nullable=True),
    sa.Column('site_code', sa.TEXT(), nullable=True),
    sa.Column('submit_date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('install', sa.Boolean(), nullable=True),
    sa.Column('change', sa.Boolean(), nullable=True),
    sa.Column('move', sa.Boolean(), nullable=True),
    sa.Column('disconnect', sa.Boolean(), nullable=True),
    sa.Column('requestor_name', sa.TEXT(), nullable=False),
    sa.Column('email', sa.TEXT(), nullable=False),
    sa.Column('telephone', sa.INTEGER(), nullable=True),
    sa.Column('department', sa.TEXT(), nullable=True),
    sa.Column('division', sa.TEXT(), nullable=True),
    sa.Column('rc', sa.TEXT(), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('room', sa.TEXT(), nullable=True),
    sa.Column('depot', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('manager_name', sa.TEXT(), nullable=False),
    sa.Column('manager_title', sa.TEXT(), nullable=True),
    sa.Column('approval', sa.Boolean(), nullable=True),
    sa.Column('floor', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('key'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
